/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tokenSol from "./Token.sol";
export type { tokenSol };
import type * as interface from "./interface";
export type { interface };
export type { AuditTrail } from "./AuditTrail";
